output_dir: output
figma_scale: 1
viewport:
  width: 1440
  height: 900
pages:
  - name: login-page
    url: https://sable-boil-40643239.figma.site/
    figma_file_key: 240oOd0LxJMkrIgCsbzZKL
    figma_node_id: "1:374"